import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// Deduplicated and sorted map
const manualMap: Record<string, string> = {
    "a couple of": "phr.",
    "a variety of": "phr.",
    "absent": "adj.",
    "abundant": "adj.",
    "accomplish": "v.",
    "acid": "n.",
    "addicted": "adj.",
    "advanced": "adj.",
    "against": "prep.",
    "alone": "adj.",
    "amateur": "n.",
    "amazing": "adj.",
    "among": "prep.",
    "ancient": "adj.",
    "apology": "n.",
    "apparent": "adj.",
    "architecture": "n.",
    "article": "n.",
    "as long as": "phr.",
    "aspect": "n.",
    "assign": "v.",
    "assume": "v.",
    "at least": "phr.",
    "at the end of": "phr.",
    "athlete": "n.",
    "atmosphere": "n.",
    "attitude": "n.",
    "auditorium": "n.",
    "average": "n.",
    "aware": "adj.",
    "background": "n.",
    "backward": "adv.",
    "bacteria": "n.",
    "be made up of": "phr.",
    "beat": "v.",
    "belief": "n.",
    "belong": "v.",
    "below": "prep.",
    "beneath": "prep.",
    "benefit": "n.",
    "beyond": "prep.",
    "blind": "adj.",
    "blow": "v.",
    "bone": "n.",
    "borrow": "v.",
    "bottom": "n.",
    "bounce": "v.",
    "brain": "n.",
    "branch": "n.",
    "break": "v.",
    "brief": "adj.",
    "bright": "adj.",
    "brilliant": "adj.",
    "broad": "adj.",
    "browse": "v.",
    "brush": "v.",
    "budget": "n.",
    "burn": "v.",
    "burst": "v.",
    "bury": "v.",
    "cafeteria": "n.",
    "camp": "n.",
    "campus": "n.",
    "cancel": "v.",
    "capture": "v.",
    "carry out": "phr.",
    "carve": "v.",
    "castle": "n.",
    "category": "n.",
    "cause": "n.",
    "cell": "n.",
    "century": "n.",
    "chain": "n.",
    "challenge": "n.",
    "championship": "n.",
    "chase": "v.",
    "cheat": "v.",
    "check": "v.",
    "choose": "v.",
    "circle": "n.",
    "claim": "v.",
    "click": "v.",
    "club": "n.",
    "coach": "n.",
    "collapse": "v.",
    "collect": "v.",
    "college": "n.",
    "combine": "v.",
    "come up with": "phr.",
    "common": "adj.",
    "compare": "v.",
    "compete": "v.",
    "complain": "v.",
    "complete": "v.",
    "complex": "adj.",
    "complicated": "adj.",
    "compose": "v.",
    "concept": "n.",
    "concern": "n.",
    "concert": "n.",
    "conclude": "v.",
    "confirm": "v.",
    "conflict": "n.",
    "confuse": "v.",
    "connect": "v.",
    "consensus": "n.",
    "consist of": "phr.",
    "consistent": "adj.",
    "constant": "adj.",
    "construct": "v.",
    "contact": "n.",
    "contain": "v.",
    "contemporary": "adj.",
    "content": "n.",
    "contest": "n.",
    "context": "n.",
    "continue": "v.",
    "contrary": "adj.",
    "contrast": "n.",
    "contribute": "v.",
    "control": "n.",
    "convenient": "adj.",
    "convey": "v.",
    "convince": "v.",
    "cope with": "phr.",
    "copy": "n.",
    "correct": "adj.",
    "cost": "n.",
    "cotton": "n.",
    "count": "v.",
    "course": "n.",
    "crack": "n.",
    "creature": "n.",
    "criticism": "n.",
    "crop": "n.",
    "crush": "v.",
    "culture": "n.",
    "cure": "v.",
    "cycle": "n.",
    "damage": "n.",
    "data": "n.",
    "deal with": "phr.",
    "decade": "n.",
    "decay": "v.",
    "decide": "v.",
    "decline": "v.",
    "decrease": "v.",
    "defeat": "v.",
    "define": "v.",
    "degree": "n.",
    "delay": "v.",
    "demand": "n.",
    "depend": "v.",
    "depth": "n.",
    "describe": "v.",
    "design": "n.",
    "desire": "n.",
    "despite": "prep.",
    "detect": "v.",
    "determine": "v.",
    "device": "n.",
    "diet": "n.",
    "difficulty": "n.",
    "diligent": "adj.",
    "direct": "adj.",
    "disappear": "v.",
    "discovery": "n.",
    "dismiss": "v.",
    "display": "v.",
    "distant": "adj.",
    "distinct": "adj.",
    "distinguish": "v.",
    "distribute": "v.",
    "disturb": "v.",
    "divide": "v.",
    "dominant": "adj.",
    "dorm": "n.",
    "draft": "n.",
    "drag": "v.",
    "drop": "v.",
    "drug": "n.",
    "dry": "adj.",
    "due": "adj.",
    "due to": "phr.",
    "earn": "v.",
    "ease": "n.",
    "effect": "n.",
    "efficient": "adj.",
    "emerge": "v.",
    "emergency": "n.",
    "emphasis": "n.",
    "employee": "n.",
    "endure": "v.",
    "energy": "n.",
    "engage": "v.",
    "enroll": "v.",
    "entire": "adj.",
    "erupt": "v.",
    "escape": "v.",
    "essay": "n.",
    "establish": "v.",
    "even though": "phr.",
    "event": "n.",
    "evident": "adj.",
    "evolutionary": "adj.",
    "evolve": "v.",
    "exact": "adj.",
    "exceed": "v.",
    "excellent": "adj.",
    "except": "prep.",
    "exchange": "v.",
    "exciting": "adj.",
    "exhibit": "v.",
    "expand": "v.",
    "expect": "v.",
    "expert": "n.",
    "expire": "v.",
    "explain": "v.",
    "explode": "v.",
    "explore": "v.",
    "expose": "v.",
    "express": "v.",
    "extend": "v.",
    "extinct": "adj.",
    "extinguish": "v.",
    "extra": "adj.",
    "extreme": "adj.",
    "fact": "n.",
    "faculty": "n.",
    "fail": "v.",
    "faint": "adj.",
    "fairly": "adv.",
    "fame": "n.",
    "familiar": "adj.",
    "fascinating": "adj.",
    "feature": "n.",
    "fee": "n.",
    "feed": "v.",
    "feel": "v.",
    "feeling": "n.",
    "female": "adj.",
    "field": "n.",
    "fight": "v.",
    "figure out": "phr.",
    "fill": "v.",
    "find out": "phr.",
    "finding": "n.",
    "fine": "adj.",
    "finish": "v.",
    "fit": "v.",
    "fix": "v.",
    "flood": "n.",
    "flow": "v.",
    "follow": "v.",
    "following": "adj.",
    "fond": "adj.",
    "forest": "n.",
    "forget": "v.",
    "form": "n.",
    "fossil": "n.",
    "freeze": "v.",
    "frequency": "n.",
    "frequent": "adj.",
    "fresh": "adj.",
    "fulfill": "v.",
    "full": "adj.",
    "fund": "n.",
    "gain": "v.",
    "gallery": "n.",
    "get along with": "phr.",
    "get rid of": "phr.",
    "giant": "adj.",
    "give up": "phr.",
    "glad": "adj.",
    "glove": "n.",
    "go through": "phr.",
    "grab": "v.",
    "grocery": "n.",
    "grow": "v.",
    "guess": "v.",
    "guide": "n.",
    "gym": "n.",
    "habit": "n.",
    "habitat": "n.",
    "hand in": "phr.",
    "handle": "v.",
    "handout": "n.",
    "happen": "v.",
    "harm": "n.",
    "harsh": "adj.",
    "harvest": "n.",
    "health": "n.",
    "healthy": "adj.",
    "heritage": "n.",
    "hide": "v.",
    "hike": "v.",
    "hint": "n.",
    "hire": "v.",
    "hold": "v.",
    "hollow": "adj.",
    "huge": "adj.",
    "hunt": "v.",
    "hurt": "v.",
    "ignore": "v.",
    "image": "n.",
    "imagine": "v.",
    "impact": "n.",
    "impress": "v.",
    "improve": "v.",
    "in case": "phr.",
    "in charge of": "phr.",
    "in order to": "phr.",
    "in other words": "phr.",
    "in the long run": "phr.",
    "include": "v.",
    "increase": "v.",
    "independent": "adj.",
    "industry": "n.",
    "infect": "v.",
    "inform": "v.",
    "ingredient": "n.",
    "inhabit": "v.",
    "injure": "v.",
    "injury": "n.",
    "insect": "n.",
    "inspire": "v.",
    "instant": "adj.",
    "instead": "adv.",
    "instruct": "v.",
    "intellect": "n.",
    "intend": "v.",
    "interested": "adj.",
    "interpret": "v.",
    "interrupt": "v.",
    "intervene": "v.",
    "interview": "n.",
    "introductory": "adj.",
    "invent": "v.",
    "involve": "v.",
    "irrelevant": "adj.",
    "island": "n.",
    "issue": "n.",
    "join": "v.",
    "journey": "n.",
    "knowledge": "n.",
    "laboratory": "n.",
    "lack": "n.",
    "landscape": "n.",
    "language": "n.",
    "last": "adj.",
    "lead to": "phr.",
    "leak": "v.",
    "leap": "v.",
    "learn": "v.",
    "lecture": "n.",
    "legend": "n.",
    "length": "n.",
    "level": "n.",
    "liberty": "n.",
    "limit": "n.",
    "link": "n.",
    "lip": "n.",
    "liquid": "n.",
    "lock": "n.",
    "look forward to": "phr.",
    "loss": "n.",
    "lost": "adj.",
    "mail": "n.",
    "main": "adj.",
    "male": "adj.",
    "manage": "v.",
    "manufacture": "v.",
    "marine": "adj.",
    "mark": "n.",
    "match": "n.",
    "mature": "adj.",
    "maximum": "n.",
    "mean": "v.",
    "means": "n.",
    "meanwhile": "adv.",
    "measure": "v.",
    "melt": "v.",
    "memory": "n.",
    "menu": "n.",
    "method": "n.",
    "midterm": "n.",
    "mild": "adj.",
    "minimum": "n.",
    "missing": "adj.",
    "mistake": "n.",
    "misunderstand": "v.",
    "mix": "v.",
    "model": "n.",
    "modern": "adj.",
    "moisture": "n.",
    "mood": "n.",
    "multitude": "n.",
    "muscle": "n.",
    "mystery": "n.",
    "narrow": "adj.",
    "nearby": "adj.",
    "necessary": "adj.",
    "neglect": "v.",
    "nerve": "n.",
    "notice": "v.",
    "nutrient": "n.",
    "obey": "v.",
    "observe": "v.",
    "obtain": "v.",
    "occupy": "v.",
    "occur": "v.",
    "offspring": "n.",
    "on account of": "phr.",
    "on the other hand": "phr.",
    "on time": "phr.",
    "once": "adv.",
    "opening": "n.",
    "opinion": "n.",
    "opponent": "n.",
    "oppose": "v.",
    "opposite": "adj.",
    "orbit": "n.",
    "organ": "n.",
    "origin": "n.",
    "outcome": "n.",
    "outline": "n.",
    "oxygen": "n.",
    "pack": "v.",
    "painting": "n.",
    "pair": "n.",
    "parent": "n.",
    "participant": "n.",
    "particle": "n.",
    "particular": "adj.",
    "password": "n.",
    "path": "n.",
    "patient": "n.",
    "pattern": "n.",
    "pause": "v.",
    "peak": "n.",
    "pedestrian": "n.",
    "percent": "n.",
    "perfect": "adj.",
    "perform": "v.",
    "permit": "v.",
    "persuade": "v.",
    "phenomenon": "n.",
    "photography": "n.",
    "pick up": "phr.",
    "plant": "n.",
    "plus": "prep.",
    "policy": "n.",
    "polite": "adj.",
    "pollute": "v.",
    "popular": "adj.",
    "portrait": "n.",
    "postpone": "v.",
    "predict": "v.",
    "prepare": "v.",
    "present": "n.",
    "preserve": "v.",
    "president": "n.",
    "pressure": "n.",
    "pretend": "v.",
    "prevent": "v.",
    "price": "n.",
    "primary": "adj.",
    "printing": "n.",
    "procedure": "n.",
    "process": "n.",
    "produce": "v.",
    "product": "n.",
    "profit": "n.",
    "profound": "adj.",
    "program": "n.",
    "progress": "n.",
    "prohibit": "v.",
    "project": "n.",
    "promote": "v.",
    "pronounce": "v.",
    "property": "n.",
    "protein": "n.",
    "protest": "v.",
    "prove": "v.",
    "provide": "v.",
    "publish": "v.",
    "punish": "v.",
    "purchase": "v.",
    "purpose": "n.",
    "puzzle": "n.",
    "quit": "v.",
    "quiz": "n.",
    "random": "adj.",
    "range": "n.",
    "rank": "n.",
    "rapid": "adj.",
    "rare": "adj.",
    "rather than": "phr.",
    "raw": "adj.",
    "reach": "v.",
    "reason": "n.",
    "recall": "v.",
    "recommend": "v.",
    "record": "n.",
    "recycle": "v.",
    "reduce": "v.",
    "refer to": "phr.",
    "referee": "n.",
    "reflect": "v.",
    "refuse": "v.",
    "regard": "v.",
    "regardless of": "phr.",
    "region": "n.",
    "regret": "v.",
    "regular": "adj.",
    "reject": "v.",
    "relationship": "n.",
    "relax": "v.",
    "release": "v.",
    "relevant": "adj.",
    "remain": "v.",
    "remind": "v.",
    "remove": "v.",
    "renew": "v.",
    "repair": "v.",
    "repeat": "v.",
    "replace": "v.",
    "represent": "v.",
    "reproduce": "v.",
    "request": "n.",
    "require": "v.",
    "rescue": "v.",
    "research": "n.",
    "reserve": "v.",
    "resistant": "adj.",
    "resource": "n.",
    "respect": "n.",
    "respond": "v.",
    "response": "n.",
    "restore": "v.",
    "restrict": "v.",
    "result": "n.",
    "result from": "phr.",
    "result in": "phr.",
    "retain": "v.",
    "retrieve": "v.",
    "return": "v.",
    "reverse": "v.",
    "review": "v.",
    "reward": "n.", // Fixed duplicate
    "risk": "n.", // Fixed duplicate
    "role": "n.", // Fixed duplicate
    "roll": "v.",
    "routine": "n.",
    "rude": "adj.",
    "rule": "n.", // Fixed duplicate
    "run": "v.",
    "safe": "adj.", // Fixed duplicate
    "sail": "v.",
    "sample": "n.", // Fixed duplicate
    "save": "v.", // Fixed duplicate
    "schedule": "n.",
    "scholar": "n.",
    "score": "n.", // Fixed duplicate
    "screen": "n.", // Fixed duplicate
    "sculpture": "n.",
    "search": "v.", // Fixed duplicate
    "secret": "adj.", // Fixed duplicate
    "seed": "n.", // Fixed duplicate
    "seek": "v.", // Fixed duplicate
    "seldom": "adv.",
    "sense": "n.", // Fixed duplicate
    "serve": "v.", // Fixed duplicate
    "service": "n.", // Fixed duplicate
    "set aside": "phr.",
    "set up": "phr.",
    "setting": "n.",
    "settle": "v.", // Fixed duplicate
    "severe": "adj.", // Fixed duplicate
    "shade": "n.",
    "shadow": "n.",
    "shake": "v.", // Fixed duplicate
    "shallow": "adj.",
    "shape": "n.", // Fixed duplicate
    "share": "v.", // Fixed duplicate
    "sharp": "adj.", // Fixed duplicate
    "shift": "v.",
    "shorten": "v.",
    "shrink": "v.",
    "significant": "adj.", // Fixed duplicate
    "silent": "adj.", // Fixed duplicate
    "similar": "adj.", // Fixed duplicate
    "simple": "adj.", // Fixed duplicate
    "single": "adj.", // Fixed duplicate
    "sink": "v.", // Fixed duplicate
    "site": "n.", // Fixed duplicate
    "sketch": "n.",
    "skill": "n.", // Fixed duplicate
    "skim": "v.",
    "skip": "v.",
    "slip": "v.", // Fixed duplicate
    "smell": "v.",
    "smooth": "adj.", // Fixed duplicate
    "so far": "phr.",
    "society": "n.", // Fixed duplicate
    "software": "n.", // Fixed duplicate
    "soil": "n.", // Fixed duplicate
    "solar": "adj.",
    "solid": "adj.", // Fixed duplicate
    "solve": "v.", // Fixed duplicate
    "sophisticated": "adj.",
    "source": "n.", // Fixed duplicate
    "species": "n.", // Fixed duplicate
    "speech": "n.", // Fixed duplicate
    "speed": "n.", // Fixed duplicate
    "spell": "v.", // Fixed duplicate
    "spend": "v.", // Fixed duplicate
    "spill": "v.",
    "spirit": "n.", // Fixed duplicate
    "split": "v.", // Fixed duplicate
    "spread": "v.", // Fixed duplicate
    "square": "n.", // Fixed duplicate
    "staff": "n.", // Fixed duplicate
    "standard": "n.", // Fixed duplicate
    "stick": "v.", // Fixed duplicate
    "stock": "n.", // Fixed duplicate
    "store": "n.", // Fixed duplicate
    "straight": "adj.", // Fixed duplicate
    "strategy": "n.", // Fixed duplicate
    "strength": "n.", // Fixed duplicate
    "stretch": "v.", // Fixed duplicate
    "strike": "v.", // Fixed duplicate
    "structure": "n.", // Fixed duplicate
    "struggle": "v.", // Fixed duplicate
    "submit": "v.", // Fixed duplicate
    "succeed": "v.", // Fixed duplicate
    "success": "n.", // Fixed duplicate
    "suggest": "v.", // Fixed duplicate
    "summary": "n.",
    "support": "v.", // Fixed duplicate
    "suppose": "v.", // Fixed duplicate
    "surface": "n.", // Fixed duplicate
    "surround": "v.", // Fixed duplicate
    "survey": "n.", // Fixed duplicate
    "suspend": "v.",
    "switch": "v.", // Fixed duplicate
    "symbol": "n.", // Fixed duplicate
    "sympathy": "n.", // Fixed duplicate
    "take advantage of": "phr.",
    "take sth. for granted": "phr.",
    "take...into": "phr.",
    "talent": "n.",
    "target": "n.", // Fixed duplicate
    "task": "n.", // Fixed duplicate
    "taste": "n.", // Fixed duplicate
    "tear": "v.",
    "technique": "n.",
    "technology": "n.",
    "telescope": "n.",
    "temperature": "n.",
    "tend": "v.",
    "text": "n.", // Fixed duplicate
    "textbook": "n.",
    "texture": "n.",
    "thanks to": "phr.",
    "theme": "n.",
    "theory": "n.",
    "therefore": "adv.",
    "thesis": "n.",
    "thick": "adj.",
    "thought": "n.",
    "threaten": "v.",
    "throat": "n.",
    "throughout": "prep.",
    "throw": "v.",
    "tiny": "adj.",
    "tool": "n.", // Fixed duplicate
    "tooth": "n.",
    "touch": "v.",
    "tough": "adj.",
    "tour": "n.",
    "toward": "prep.",
    "trace": "n.",
    "track": "n.",
    "trade": "n.",
    "training": "n.",
    "transport": "n.",
    "trap": "n.",
    "treasure": "n.",
    "treat": "v.",
    "trend": "n.",
    "trick": "n.",
    "trust": "n.",
    "truth": "n.",
    "twinkle": "v.",
    "under some circumstances": "phr.",
    "underground": "adj.",
    "understanding": "n.",
    "uniform": "n.",
    "unique": "adj.",
    "unit": "n.",
    "universe": "n.",
    "unless": "conj.",
    "unlike": "prep.",
    "until": "prep.",
    "upload": "v.",
    "upset": "adj.",
    "urgent": "adj.",
    "value": "n.", // Fixed duplicate
    "vary": "v.",
    "vast": "adj.",
    "victim": "n.",
    "view": "n.",
    "virus": "n.",
    "vitamin": "n.",
    "voice": "n.",
    "voluntary": "adj.",
    "vote": "v.",
    "wait": "v.",
    "warn": "v.",
    "waste": "n.",
    "wave": "v.",
    "wealthy": "adj.",
    "website": "n.",
    "weight": "n.",
    "wet": "adj.",
    "wild": "adj.",
    "willing": "adj.",
    "win": "v.",
    "within": "prep.",
    "worn": "adj.",
    "worry": "v.",
    "worship": "v.",
    "worth": "adj.",
    "wrap": "v."
};

async function main() {
    const fs = require('fs');
    let missingList: string[] = [];

    try {
        const content = fs.readFileSync('missing_pos_words.json', 'utf8');
        missingList = JSON.parse(content);
    } catch (e) {
        console.log("No missing_pos_words.json found, skipping patch.");
        return;
    }

    console.log(`Processing ${missingList.length} words...`);

    let updated = 0;

    for (const word of missingList) {
        let pos = manualMap[word];

        // Heuristics
        if (!pos) {
            if (word.endsWith('tion') || word.endsWith('ment') || word.endsWith('ness') || word.endsWith('ity') || word.endsWith('ance') || word.endsWith('ence') || word.endsWith('ist') || word.endsWith('sion') || word.endsWith('er') || word.endsWith('or') || word.endsWith('ure') || word.endsWith('gy') || word.endsWith('phy') || word.endsWith('my') || word.endsWith('th')) pos = 'n.';
            else if (word.endsWith('ize') || word.endsWith('ise') || word.endsWith('ate') || word.endsWith('fy')) pos = 'v.';
            else if (word.endsWith('ous') || word.endsWith('ive') || word.endsWith('al') || word.endsWith('ic') || word.endsWith('ful') || word.endsWith('ble') || word.endsWith('less') || word.endsWith('ant') || word.endsWith('ent')) pos = 'adj.';
            else if (word.endsWith('ly')) pos = 'adv.';
        }

        if (pos) {
            await prisma.word.update({
                where: { text: word },
                data: { partOfSpeech: pos }
            });
            updated++;
        }
    }

    console.log(`Updated POS for ${updated} words.`);
}

main()
    .catch(e => {
        console.error(e);
        process.exit(1);
    })
    .finally(async () => {
        await prisma.$disconnect();
    });
